import type { NovelWiki } from "@lnw/schema";
import { Paragraphs } from "../../components/common";
import { href } from "../../router";
import { formatDate, PROVIDER_LABEL } from "../../wiki";
import { ArcBar } from "./Arcs";
import { CharacterCard } from "./Characters";

export function Overview({ wiki }: { wiki: NovelWiki }) {
  const cast = (["protagonist", "main", "antagonist"] as const).flatMap((role) =>
    wiki.characters.filter((c) => c.role === role),
  );
  const stats = [
    { label: "Characters", value: wiki.characters.length, to: "characters" },
    { label: "Arcs", value: wiki.arcs.length, to: "arcs" },
    { label: "Locations", value: wiki.locations.length, to: "locations" },
    { label: "Chapters read", value: wiki.chapterCount, to: "arcs" },
  ];
  const { provider, model } = wiki.generatedBy;

  return (
    <div className="stack">
      {wiki.premise && (
        <section>
          <h2>Premise</h2>
          <Paragraphs text={wiki.premise} />
        </section>
      )}

      <ul className="stats">
        {stats.map((s) => (
          <li key={s.label}>
            <a href={href("n", wiki.id, s.to)}>
              <span className="stats__value">{s.value}</span>
              <span className="stats__label">{s.label}</span>
            </a>
          </li>
        ))}
      </ul>

      {wiki.plotOverview && (
        <section>
          <h2>Plot overview</h2>
          <Paragraphs text={wiki.plotOverview} />
        </section>
      )}

      {wiki.arcs.length > 0 && (
        <section>
          <h2>Story arcs</h2>
          <ArcBar wiki={wiki} />
        </section>
      )}

      {cast.length > 0 && (
        <section>
          <h2>Main cast</h2>
          <ul className="card-grid">
            {cast.map((c) => (
              <li key={c.id}>
                <CharacterCard wiki={wiki} character={c} />
              </li>
            ))}
          </ul>
        </section>
      )}

      <p className="muted small">
        {provider === "manual" ? "Written by hand" : `Generated by ${PROVIDER_LABEL[provider]}${model ? ` (${model})` : ""}`}{" "}
        · updated {formatDate(wiki.updatedAt)}
      </p>
    </div>
  );
}
